title: <p align="center"> Gouthami C </p>
logo: /assets/img/logo.png

description:
  <p align="center">
#   <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/gouthami-c-970a76113/">LinkedIn</a> |
  <a href="https://github.com/Gouthami567">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Working in data science domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
